###################
# LinkXNect.cmake #
###################

SET(CMAKE_FIND_LIBRARY_SUFFIXES ".dll.a" ".a" ".lib")

SET(Caffe_DEPENDENCIES_LIB_DIR "${Caffe_DEPENDENCIES_DIR}/lib")
SET(Caffe_DEPENDENCIES_VC14_LIB_DIR "${Caffe_DEPENDENCIES_DIR}/x64/vc14/lib")
SET(Caffe_LIB_DIR "${Caffe_ROOT_DIR}/build/lib")

FIND_LIBRARY(boost_python_LIBRARY boost_python-vc140-mt-1_61 HINTS ${Caffe_DEPENDENCIES_LIB_DIR})
FIND_LIBRARY(boost_system_LIBRARY boost_system-vc140-mt-1_61 HINTS ${Caffe_DEPENDENCIES_LIB_DIR})
FIND_LIBRARY(boost_thread_LIBRARY boost_thread-vc140-mt-1_61 HINTS ${Caffe_DEPENDENCIES_LIB_DIR})
FIND_LIBRARY(caffe_LIBRARY caffe HINTS ${Caffe_LIB_DIR})
FIND_LIBRARY(caffehdf5_LIBRARY caffehdf5 HINTS ${Caffe_DEPENDENCIES_LIB_DIR})
FIND_LIBRARY(caffehdf5_hl_LIBRARY caffehdf5_hl HINTS ${Caffe_DEPENDENCIES_LIB_DIR})
FIND_LIBRARY(caffezlib_LIBRARY caffezlib HINTS ${Caffe_DEPENDENCIES_LIB_DIR})
FIND_LIBRARY(caffeproto_LIBRARY caffeproto HINTS ${Caffe_LIB_DIR})
FIND_LIBRARY(gflags_LIBRARY gflags HINTS ${Caffe_DEPENDENCIES_LIB_DIR})
FIND_LIBRARY(glog_LIBRARY glog HINTS ${Caffe_DEPENDENCIES_LIB_DIR})
FIND_LIBRARY(libopenblas_LIBRARY NAMES libopenblas HINTS ${Caffe_DEPENDENCIES_LIB_DIR})
FIND_LIBRARY(libprotobuf_LIBRARY libprotobuf HINTS ${Caffe_DEPENDENCIES_LIB_DIR})
FIND_LIBRARY(mongoose_LIBRARY mongoose HINTS "${XNect_ROOT_DIR}/extern/mongoose/mongoose/lib/vc140")
FIND_LIBRARY(OpenCV_CALIB3D_LIBRARY opencv_calib3d310 HINTS ${Caffe_DEPENDENCIES_VC14_LIB_DIR})
FIND_LIBRARY(OpenCV_CORE_LIBRARY opencv_core310 HINTS ${Caffe_DEPENDENCIES_VC14_LIB_DIR})
FIND_LIBRARY(OpenCV_HIGHGUI_LIBRARY opencv_highgui310 HINTS ${Caffe_DEPENDENCIES_VC14_LIB_DIR})
FIND_LIBRARY(OpenCV_IMGCODECS_LIBRARY opencv_imgcodecs310 HINTS ${Caffe_DEPENDENCIES_VC14_LIB_DIR})
FIND_LIBRARY(OpenCV_IMGPROC_LIBRARY opencv_imgproc310 HINTS ${Caffe_DEPENDENCIES_VC14_LIB_DIR})
FIND_LIBRARY(XNect_LIBRARY XNECT HINTS "${XNect_ROOT_DIR}/extern/xnect/lib/vc140")

TARGET_LINK_LIBRARIES(${targetname}
${boost_python_LIBRARY}
${boost_system_LIBRARY}
${boost_thread_LIBRARY}
${caffe_LIBRARY}
${caffehdf5_LIBRARY}
${caffehdf5_hl_LIBRARY}
${caffezlib_LIBRARY}
${caffeproto_LIBRARY}
${gflags_LIBRARY}
${glog_LIBRARY}
${libopenblas_LIBRARY}
${libprotobuf_LIBRARY}
${mongoose_LIBRARY}
${OpenCV_CALIB3D_LIBRARY}
${OpenCV_CORE_LIBRARY}
${OpenCV_HIGHGUI_LIBRARY}
${OpenCV_IMGCODECS_LIBRARY}
${OpenCV_IMGPROC_LIBRARY}
${XNect_LIBRARY}
)
